name: Run echo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to upload datapack'
        type: environment
        required: true

jobs:
  check-env:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.env }}
    steps:
      - id: step1
        name: 'Set Output'
        run: |
          if ${{ inputs.environment == 'development' }}; then
            echo "env=dev" >> "$GITHUB_OUTPUT"
          else
            echo "env=${{ inputs.inputs.environment }}" >> "$GITHUB_OUTPUT"

  development:
    runs-on: ubuntu-latest
    needs: check-env
    steps:
    - name: 'Setup Config'
      run: echo ${{ needs.check-env.outputs.output1 }}
