name: Run echo

on:
  workflow_dispatch:
    inputs:
      client_assets:
        description: 'Client'
        required: false
        default: false
        type: boolean
      data_only:
        description: 'Data'
        required: false
        type: boolean
        default: true 

env:
  CI_LAUNCHER_LOG: ${{ inputs.data_only }}
  CI_ENVIRONMENT_NAME: development

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
    - name: 'Setup Config'
      # if: ${{ inputs.client_assets != true || inputs.data_only == true }}
      run: ./a.sh
