name: Run echo

on:
  push:
    branches:
      - 'stag-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  development:
    runs-on: ubuntu-latest
    environments:
      name: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    steps:
    - name: 'echo'
      run: 'echo $CHUONG'
      env:
        CHUONG: ${{ secrets.CHUONG }}
