name: Run echo

on:
  push:

jobs:
  development:
    runs-on: ubuntu-latest
    environments:
      name: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    steps:
    - name: 'echo'
      run: 'echo $CHUONG'
      env:
        CHUONG: ${{ secrets.CHUONG }}
