name: Run echo

on:
  workflow_dispatch:
    inputs:
      # environment:
      #   description: 'Environment to run tests against'
      #   required: true
      #   type: choice
      #   default: 'staging'
      #   options:
      #   - staging
      #   - production
      environment:
        description: 'Environment to run against'
        type: environment
        default: development
        required: true
      test_cases:
        description: 'A Test Case is a set of actions executed to verify a particular feature or functionality of your software application.'
        required: true
        type: choice
        default: 'smoke-test'
        options:
        - smoke-test

jobs:
  development:
    # uses: ./.github/workflows/template.yml
    # with:
    #   environment: development
    #   build_options: "'${{ inputs.test_cases }} && ls -a'"
    #   image_repository: chuong
  # chuong:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print the input name to STDOUT
  #       run: ls -a

    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c'
    - name: 'Setup DataPack Config'
      run: |
        ./test.sh ${{ inputs.environment }}
        #case ${{ inputs.environment }} in
        #  "development") branch=main;;
        #  "staging") branch=staging;;
        #  "production") branch=production;;
        #esac

        #echo "data_pack_branch=$branch"
        #echo ${{ secrets.CHUONG }} | sed 's/./& /g'
