name: Run echo

on:
  workflow_dispatch:
    inputs:
      client_assets:
        description: 'Client'
        required: false
        default: false
        type: string
      data_only:
        description: 'Data'
        required: false
        type: string

jobs:
  development:
    runs-on: ubuntu-latest
    if: ${{ inputs.client_assets != 'true' }}
    needs: check-env
    steps:
    - name: 'Setup Config'
      run: echo "Running"
