name: Run echo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to upload datapack'
        type: environment
        required: true

jobs:
  check-env:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.env }}
    steps:
      - id: step1
        name: 'Set Output'
        run: |
          if ${{ inputs.environment == 'development' }}; then
            # echo "### Not support development Please check repo data" >> $GITHUB_STEP_SUMMARY
            echo "::notice::Not support development Please check repo data"
            exit 0
          else
            echo "env=${{ inputs.environment }}" >> "$GITHUB_OUTPUT"
          fi

  development:
    runs-on: ubuntu-latest
    if: ${{ inputs.environment != 'development' }}
    needs: check-env
    steps:
    - name: 'Setup Config'
      run: echo ${{ needs.check-env.outputs.output1 }}
