name: Run echo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        default: 'staging'
        options:
        - staging
        - production
      test_cases:
        description: 'A Test Case is a set of actions executed to verify a particular feature or functionality of your software application.'
        required: true
        type: choice
        default: 'smoke-test'
        options:
        - smoke-test

jobs:
  development:
    uses: ./.github/workflows/template.yml
    with:
      environment: development
      build_options: "'${{ inputs.test_cases }} && ls -a'"
