name: Run echo

on:
  workflow_dispatch:
  push:
    branches:
      - 'stag-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
      - name: 'echo'
        run: 'echo $CHUONG'
        env:
          CHUONG: ${{ secrets.CHUONG }}
