name: Run echo

on:
  workflow_dispatch:
    inputs:
      local:
        description: 'Build Launcher to local'
        default: true
        type: boolean
      internal:
        description: 'Build Launcher to internal'
        default: true
        type: boolean
      dev:
        description: 'Build Launcher to development'
        default: true
        type: boolean
      dev2:
        description: 'Build Launcher to development 2'
        default: true
        type: boolean
      dev3:
        description: 'Build Launcher to development 3'
        default: true
        type: boolean
      staging:
        description: 'Build Launcher to statging'
        default: true
        type: boolean
      production:
        description: 'Build Launcher to production'
        default: true
        type: boolean

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c'
    - name: 'Setup Config'
      run: ./a.sh 
