name: Run echo

on:
  workflow_dispatch:
    inputs:
      client_assets:
        description: 'Client'
        required: false
        default: false
        type: boolean
      data_only:
        description: 'Data'
        required: false
        type: boolean
        default: true 

env:
  CI_LAUNCHER_LOG: ${{ inputs.data_only }}
  CI_ENVIRONMENT_NAME: development

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
    # - name: 'Setup Config'
    #   # if: ${{ inputs.client_assets != true || inputs.data_only == true }}
    #   run: ./a.sh
    - name: 'Setup Python'
      uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b #v4.6.0
      with:
        python-version: '3.10'

    - name: 'Install dbx'
      run: 'pip install dbx'

    - name: 'Upload folder'
      run: 'dbx --help'
