name: Nightly Release

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_REPOSITORY: chuong-lh/test
  DOCKER_FILE: Dockerfile

jobs:
  release:
    name: Push Docker image to GHCR.IO
    runs-on: ubuntu-latest

    # Only this job needs id-token: write for cosign to push signatures using keyless signing
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: 'Checkout Repo With Submodule'
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' #v3.1.0

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325' #v2.2.1

      - name: 'Login to GitHub Container Registry'
        uses: 'docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9' #v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'syft-installer'
        uses: 'anchore/sbom-action/download-syft@422cb34a0f8b599678c41b21163ea6088edb2624' #v0.14.1

      - name: 'cosign-installer'
        uses: 'sigstore/cosign-installer@9e9de2292db7abb3f51b7f4808d98f0d347a8919' #2.0.1

      - name: 'Build and push Docker image'
        uses: 'docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3' #v3.3.0
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          platforms: linux/amd64
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:nightly"

      - name: 'Generate and Push signed SBOM'
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          syft packages ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:nightly -o spdx > latest.spdx
          # This uploads the sbom
          cosign attach sbom --sbom latest.spdx ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:nightly
          # This signs the sbom
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY --attachment sbom ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:nightly
