name: Test

on:
  pull_request:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    # permissions:
    #   contents: 'read'
    #   id-token: 'write'

    # environment:
    #   name: production

    steps:

    #   - name: Set up Cloud SDK
    #     uses: google-github-actions/setup-gcloud@v0

      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: user/app:latest
          push: false
          sbom: true

      -
        name: Test
        run: |
          docker inspect user/app:latest
