name: Test

on:
  pull_request:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    # permissions:
    #   contents: 'read'
    #   id-token: 'write'

    # environment:
    #   name: production

    steps:

    #   - name: Set up Cloud SDK
    #     uses: google-github-actions/setup-gcloud@v0

      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: syft-installer
        uses: anchore/sbom-action/download-syft@v0.13.1

      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.8.1

      -
        name: Build
        uses: docker/build-push-action@v4
        id: build
        with:
          context: .
          tags: chuonglh/test:latest
          push: true

      - name: Generate and Push signed SBOM for jx-boot
        continue-on-error: true
        env:
          VERSION: ${{ steps.prep.outputs.version }}
        run: |
          syft chuonglh/test:latest --scope all-layers -o spdx-json > sbom.json
          cosign attach sbom --sbom sbom.json chuonglh/test@${{ steps.build.outputs.digest }}
          rm -f sbom.json
