name: Nightly Release

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_REPOSITORY: chuong-lh/test
  DOCKER_FILE: Dockerfile

jobs:
  release:
    name: Push Docker image to GHCR.IO
    runs-on: ubuntu-latest

    # Only this job needs id-token: write for cosign to push signatures using keyless signing
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: 'Checkout Repo With Submodule'
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' #v3.1.0

      - name: 'Set up QEMU'
        uses: 'docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18' #v2.1.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325' #v2.2.1

      - name: 'Login to GitHub Container Registry'
        uses: 'docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9' #v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'cosign-installer'
        uses: 'sigstore/cosign-installer@9e9de2292db7abb3f51b7f4808d98f0d347a8919' #v3.0.2

      - name: 'Build and push Docker image'
        id: 'build-and-push'
        uses: 'docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671' #v4.0.0
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:nightly"

      - name: 'Generate and Push signed SBOM'
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}@${{ steps.build-and-push.outputs.digest }}
