name: Test

on:
  pull_request:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    # permissions:
    #   contents: 'read'
    #   id-token: 'write'

    # environment:
    #   name: production

    steps:
      - name: Test cmd
        env:
          IMAGE: ${{ (github.ref_name == 'main') && fromJSON('main') || 'dev' }}
          CI_ENVIRONMENT_NAME: development
          CI_BUILD_VERSION: 22
        run: |
           # set "OUTPUT_PATH=outputs\%CI_ENVIRONMENT_NAME%\%CI_BUILD_VERSION%\%FOLDER_NAME%"
           # echo %OUTPUT_PATH%
           # echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
           echo ${IMAGE}
           # echo ${{ github.run_number }}

    #   - name: Set up Cloud SDK
    #     uses: google-github-actions/setup-gcloud@v0

    #     with:
    #       buildkitd-flags: --debug

    #   -
    #     name: Login to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    #   - name: syft-installer
    #     uses: anchore/sbom-action/download-syft@v0.13.1

    #   - name: cosign-installer
    #     uses: sigstore/cosign-installer@v2.8.1

    #   -
    #     name: Build
    #     uses: docker/build-push-action@v4
    #     id: build
    #     with:
    #       context: .
    #       tags: chuonglh/test:latest
    #       push: true

    #   - name: Generate and Push signed SBOM for jx-boot
    #     continue-on-error: true
    #     env:
    #       VERSION: ${{ steps.prep.outputs.version }}
    #     run: |
    #       syft chuonglh/test:latest --scope all-layers -o spdx-json > sbom.json
    #       rm -f sbom.json


